version: "3.8"

services:
  backend:
    build: .
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/urlShortener
      - JWT_SECRET=supersecretkey
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    restart: "no"
    volumes:
    #   - .:/app
      - /app/node_modules
  mongo:
    image: mongo:7
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: urlShortener
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
